version: '3.8'

services:
  dev:
    build: .
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev
    ports:
      - "3000:3000"
    
  test:
    build: .
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=test
    command: npm test
    
  build:
    build: .
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run build

  cli:
    build: .
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    entrypoint: ["node", "dist/cli.js"]